title: 抚七 kilroy
subtitle: "记录与分享技术的每一刻,同时享受生活的点滴"
description: "这是抚七kilroy的个人博客，记录与分享技术的每一刻、学习笔记及生活随笔。"
keywords: "抚七kilroy, 前后端开发,C++,游戏开发, Web技术, 博客, 学习笔记"
author: 抚七kilroy
language: zh-CN
timezone: ""

# 注意这里要包含仓库名
url: https://fuqikilroy.github.io/HEXO/
root: /HEXO/ # 注意这里以斜杠开头和结尾

permalink: ":year/:month/:day/:title/"
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: null

new_post_name: ":year-:month-:day-:title.md"
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: ture
relative_link: false
future: true

syntax_highlighter: "highlight.js"
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
  exclude_languages: ["mermaid"]
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
  exclude_languages: ["mermaid"]

index_generator:
  path: ""
  per_page: 10
  order_by: "-date"
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 7
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly

deploy:
  type: git
  repo: https://github.com/fuqikilroy/HEXO.git
  branch: gh-pages 

# 本地搜索
search:
  path: search.xml
  field: all
  content: true

# 插件
markdown:
  plugins:
    - "@renbaoshuo/markdown-it-katex"


# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    # 由于预览模型网页没用了，所以下了几个：wanko小狗，miku，koharu
    use: live2d-widget-model-koharu # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right #控制看板娘位置
    width: 150 #控制看板娘大小
    height: 300 #控制看板娘大小
  mobile:
    show: false # 手机中是否展示
